name: Frontend

on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run frontend tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            client/
          sparse-checkout-cone-mode: false
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: ./client/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: ./client
        run: pnpm i
      - name: Install playwright
        working-directory: ./client
        run: pnpm exec playwright install --with-deps
      - name: Test with coverage
        working-directory: ./client
        run: pnpm vitest run --coverage
        env:
          MODE: CI
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./client/coverage/lcov.info
